services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5332:5432"
    env_file: .env

volumes:
  postgres_data:
  static_volume:
  frontend_build:
